# Generated by Django 3.2.5 on 2021-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('player1_card', models.PositiveIntegerField(verbose_name=5)),
                ('player2_card', models.PositiveIntegerField(verbose_name=4)),
                ('result', models.CharField(choices=[('승리', '승리'), ('패배', '패배'), ('무승부', '무승부')], max_length=50)),
                ('my_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
