# Generated by Django 3.2.5 on 2021-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgame',
            name='rule',
            field=models.CharField(choices=[('숫자가 더 큰 사람', '숫자가 더 큰 사람'), ('숫자가 더 적은 사람', '숫자가 더 적은 사람')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='player1_card',
            field=models.PositiveIntegerField(verbose_name=1),
        ),
    ]
